const TYPES = {
    LoginInterface: Symbol.for("LoginInterface"),
    CustomMiddleware: Symbol.for("CustomMiddleware"),
    ListPetInterface: Symbol.for("ListPetInterface"),
    ListUserInterface: Symbol.for("ListUserInterface"),
    CreatePetInterface: Symbol.for("CreatePetInterface"),
    UpdatePetInterface: Symbol.for("UpdatePetInterface"),
    DeletePetInterface: Symbol.for("DeletePetInterface"),
    ListOwnerInterface: Symbol.for("ListOwnerInterface"),
    CreateUserInterface: Symbol.for("CreateUserInterface"),
    UpdateUserInterface: Symbol.for("UpdateUserInterface"),
    DeleteUserInterface: Symbol.for("DeleteUserInterface"),
    CepProviderInterface: Symbol.for("CepProviderInterface"),
    FindPetByIdInterface: Symbol.for("FindPetByIdInterface"),
    ListPetTypeInterface: Symbol.for("ListPetTypeInterface"),
    CreateOwnerInterface: Symbol.for("CreateOwnerInterface"),
    DeleteOwnerInterface: Symbol.for("DeleteOwnerInterface"),
    UpdateOwnerInterface: Symbol.for("UpdateOwnerInterface"),
    FindUserByIdInterface: Symbol.for("FindUserByIdInterface"),
    FindOwnerByIdInterface: Symbol.for("FindOwnerByIdInterface"),
    CreatePetTypeInterface: Symbol.for("CreatePetTypeInterface"),
    UpdatePetTypeInterface: Symbol.for("UpdatePetTypeInterface"),
    DeletePetTypeInterface: Symbol.for("DeletePetTypeInterface"),
    PetRepositoryInterface: Symbol.for("PetRepositoryInterface"),
    UserRepositoryInterface: Symbol.for("UserRepositoryInterface"),
    OwnerRepositoryInterface: Symbol.for("OwnerRepositoryInterface"),
    FindPetTypeByIdInterface: Symbol.for("FindPetTypeByIdInterface"),
    PetTypeRepositoryInterface: Symbol.for("PetTypeRepositoryInterface"),
};

export default TYPES;